### ISSUE TITLE
Request to update to the latest version of anki

### ISSUE THREAD

**Issue by kanjieater** [LumenYoung/anki_sync_server#1]
I was hoping to use a dockerized version of anki for a sync server as well, and was hoping this could be kept up to date with the latest version of anki.

**Comment by LumenYoung** [comment]
Hi @kanjieater, thanks for reaching out. I've updated the Dockerfile and pre-bulit image. The new image name at register is `lumeny/anki_sync_server:latest`, which you should take care if you are not building the image yourself. I've tested it on my side and it works.
